name: rtd_on_track
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.1.0
  flutter_bloc: ^9.1.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.0
  flutter_background_service: ^5.0.4
  path_provider: ^2.1.2
  intl: ^0.20.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  logger: ^2.5.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

